# Runs automated tests upon pushing to main

name: test-push-main

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Running tests for main push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-verion: "3.11"
          architecture: "x64"

      - name: Importing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running tests
        run: |
          python -m pytest
          pip install pytest pytest-cov
          python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
