# Runs automated tests upon a pull request

name: test-pull-request

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    name: Running tests on pull request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Importing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running tests
        run: |
          python -m pytest
