FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir pymongo python-dotenv

# Copy the text index script
COPY ./mongo/create_text_index.py /app/create_text_index.py

# Run the script
CMD ["python", "create_text_index.py"]
