FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY processing/db_loader.py .
COPY message_queue/message_queue.py ./message_queue/

ENTRYPOINT ["python", "db_loader.py"]
CMD []