FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY processing/chunking.py .
COPY message_queue/message_queue.py ./message_queue/

CMD ["python", "chunking.py"]