FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m spacy download en_core_web_sm

COPY processing/extract_keywords.py .
COPY message_queue/message_queue.py ./message_queue/

CMD ["python", "extract_keywords.py"]