params:
  model: "openai:gpt-4.1-nano"
  temperature: 0.2
  top_p: 0.9
  max_retries: 1

system_prompt: "planner1.txt"

metadata:
  model_name: "openai:gpt-4.1-nano"
  type: "planner"
  version_name: "planner/openai:gpt-4.1-nano/v1"

logs:
  out_file: "logs/planner_model/output.txt"
  err_file: "logs/planner_model/error.txt"
