params:
  model: "openai:gpt-4.1-nano"
  temperature: 0.2
  top_p: 0.9
  max_retries: 1

system_prompt: "core1.txt"

metadata:
  model_name: "openai:gpt-4.1-nano"
  type: "core"
  version_name: "core/openai:gpt-4.1-nano/v1"

system_prompt_file: "prompts/core1.txt"

logs:
  out_file: "logs/core_model/output.txt"
  err_file: "logs/core_model/error.txt"
