params:
  num_results: 5

metadata:
  model_name: "duckduckgosearch"
  type: "search"
  version_name: "search/duckduckgosearch/v1"

logs:
  out_file: "logs/search/output.txt"
  err_file: "logs/search/error.txt"
