# Runs automated tests for agent server
name: test-agent-server

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ["src/backend/agent/**"]
  push:
    branches: 
      - main
      - "features/**"
    paths: ["src/backend/agent/**"]

jobs:
  run-tests:
    name: Running tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/agent/requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        working-directory: src/backend/agent
        run: |
          python -m pytest --doctest-modules --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html